modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/ExpensiveKoala/Fishing-Real/issues"
[[mods]]
modId="fishingreal"
version="${version}"
displayName="Fishingreal"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fishing-real"
logoFile="icon.png"
authors="ExpensiveKoala, ThatGravyBoat, AlexNijjar"
description='''
A mod which allows you to reel in real fish instead of the fish in item form.
'''
[[mixins]]
config = "fishingreal.mixins.json"
[[dependencies.fishingreal]]
   modId="neoforge"
   type="required"
   versionRange="[21.0,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.fishingreal]]
   modId="minecraft"
   type="required"
   versionRange="[1.21,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.fishingreal]]
   modId="aquaculture"
   type="optional"
   versionRange="[1.21-2.7.5,)"
   ordering="NONE"
   side="BOTH"
