modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/ExpensiveKoala/Fishing-Real/issues"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fishing-real"
logoFile="icon.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]]
   modId="neoforge"
   type="required"
   versionRange="[${neoforge_version},)"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="minecraft"
   type="required"
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"