name: Release
on: [
  workflow_dispatch
]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - run: chmod +x ./gradlew

      - name: Release
        run: ./gradlew :fabric:modrinth :neoforge:modrinth :fabric:curseforge :neoforge:curseforge
        env:
          CURSE_TOKEN: ${{ secrets.CURSE_TOKEN }}
          CURSE_PROJECT: ${{ secrets.CURSE_PROJECT }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_PROJECT: ${{ secrets.MODRINTH_PROJECT }}